<template>
    <div class="payment-panel">
        <div class="payment-header">
            <div class="payment-icon">
                <q-icon name="payment" />
            </div>
            <div class="payment-title">Оплата документа</div>
        </div>
        
        <div class="payment-content">
            <div class="payment-info">
                <div class="amount-label">Стоимость создания</div>
                <div class="amount-value">{{ formatPrice(amount) }} ₽</div>
            </div>
        </div>

        <!-- Поле email -->
        <div class="email-input-section">
            <div class="custom-input-wrapper">
                <label class="custom-input-label">Email для чека</label>
                <div class="custom-input-container">
                    <input
                        v-model="userEmail"
                        type="email"
                        class="custom-input"
                        placeholder="example@mail.ru"
                        pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}"
                        title="Введите корректный email адрес"
                        required
                    />
                    <q-icon name="email" class="input-icon" />
                </div>
            </div>
        </div>

        <!-- Чекбокс согласия на обработку персональных данных -->
        <div class="privacy-consent-section">
            <label class="privacy-consent-wrapper">
                <input
                    v-model="privacyConsent"
                    type="checkbox"
                    class="privacy-checkbox"
                    required
                />
                <span class="privacy-consent-text">
                    Я согласен на обработку персональных данных
                </span>
            </label>
        </div>

        <!-- Кнопка оплаты -->
        <div class="payment-button-section">
            <q-btn
                label="Оплатить"
                color="primary"
                size="lg"
                :loading="loading || isSavingUserContact"
                :disable="!isEmailValid || !privacyConsent"
                @click="handlePayment"
                class="payment-btn"
                unelevated
                no-caps
            />
        </div>
        
        <!-- Информация о территориальных ограничениях -->
        <div class="payment-restriction-notice">
            <q-icon name="info" class="restriction-icon" />
            <span>Оплата доступна с IP-адресов Российской Федерации</span>
        </div>
        
        <!-- Сообщение об ошибке -->
        <div v-if="errorMessage" class="error-message">
            <q-icon name="error" class="error-icon" />
            {{ errorMessage }}
        </div>
    </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import { apiClient } from '@/composables/api';
import { useQuasar } from 'quasar';
import { useTelegramWebApp } from '@/composables/telegramWebApp';

const $q = useQuasar();

// Telegram WebApp для определения среды
const { isTelegramWebApp } = useTelegramWebApp();

const props = defineProps({
    amount: {
        type: Number,
        required: true
    },
    document: {
        type: Object,
        required: true
    },
    user: {
        type: Object,
        required: true
    }
});

const emit = defineEmits(['payment']);

const loading = ref(false);
const errorMessage = ref('');
const isSavingUserContact = ref(false);

// Состояния для email и согласия
const userEmail = ref('');
const privacyConsent = ref(false);

// Computed свойство для проверки валидности email
const isEmailValid = computed(() => {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    const trimmedEmail = userEmail.value.trim();
    
    // Проверяем формат и что email не автогенерированный
    return trimmedEmail && 
           emailRegex.test(trimmedEmail) && 
           !trimmedEmail.endsWith('@auto.user') && 
           !trimmedEmail.endsWith('@linked.user');
});

// Загрузить данные пользователя для контактов
const loadUserContactData = async () => {
    try {
        // Получаем данные пользователя из пропсов
        const user = props.user;
        if (user) {
            // Проверяем, является ли email автогенерированным
            const isAutoGenerated = user.email && (user.email.endsWith('@auto.user') || user.email.endsWith('@linked.user'));
            userEmail.value = isAutoGenerated ? '' : (user.email || '');
            privacyConsent.value = user.privacy_consent || false;
        }
    } catch (error) {
        console.error('Ошибка при загрузке данных пользователя:', error);
    }
};

// Сохранить контактные данные пользователя
const saveUserContact = async () => {
    if (!userEmail.value.trim()) {
        $q.notify({
            type: 'negative',
            message: 'Введите email адрес',
            position: 'top'
        });
        return false;
    }

    // Проверка формата email
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(userEmail.value.trim())) {
        $q.notify({
            type: 'negative',
            message: 'Введите корректный email адрес',
            position: 'top'
        });
        return false;
    }

    // Проверка на автогенерированный email
    if (userEmail.value.trim().endsWith('@auto.user') || userEmail.value.trim().endsWith('@linked.user')) {
        $q.notify({
            type: 'negative',
            message: 'Введите действительный email адрес для получения чека',
            position: 'top'
        });
        return false;
    }

    if (!privacyConsent.value) {
        $q.notify({
            type: 'negative',
            message: 'Необходимо дать согласие на обработку персональных данных',
            position: 'top'
        });
        return false;
    }

    isSavingUserContact.value = true;

    try {
        const response = await fetch('/api/user/update-contact', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Accept': 'application/json',
                'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
            },
            body: JSON.stringify({
                email: userEmail.value.trim(),
                privacy_consent: privacyConsent.value
            })
        });

        const data = await response.json();

        if (!response.ok) {
            throw new Error(data.error || `HTTP Error: ${response.status}`);
        }

        if (data.success) {
            return true;
        } else {
            throw new Error(data.error || 'Ошибка при сохранении данных');
        }

    } catch (error) {
        console.error('Ошибка при сохранении контактных данных:', error);
        $q.notify({
            type: 'negative',
            message: error.message || 'Ошибка при сохранении контактных данных',
            position: 'top'
        });
        return false;
    } finally {
        isSavingUserContact.value = false;
    }
};

const formatPrice = (price) => {
    return new Intl.NumberFormat('ru-RU').format(price);
};

const handlePayment = async () => {
    try {
        loading.value = true;
        errorMessage.value = '';

        console.log('=== Начало процесса оплаты документа ===');
        console.log('Email:', userEmail.value);
        console.log('Согласие:', privacyConsent.value);

        // Сначала сохраняем контактные данные
        console.log('Сохраняем контактные данные...');
        const contactSaved = await saveUserContact();
        if (!contactSaved) {
            console.log('Контактные данные не сохранены');
            return;
        }
        console.log('Контактные данные сохранены успешно');

        // Создаем заказ
        console.log('Создаем заказ...');
        const orderResponse = await apiClient.post(route('orders.process', props.document.id));

        if (!orderResponse.success || !orderResponse.order_id) {
            throw new Error('Ошибка при создании заказа');
        }

        console.log('Заказ создан успешно, ID:', orderResponse.order_id);

        // Создаем платеж ЮКасса и получаем URL для оплаты
        console.log('Создаем платеж ЮКасса...');
        const paymentResponse = await apiClient.post(route('api.payment.yookassa.create', orderResponse.order_id));

        if (paymentResponse.success && paymentResponse.confirmation_url) {
            console.log('Платеж создан успешно, URL:', paymentResponse.confirmation_url);
            // Перенаправляем на оплату ЮКасса
            if (isTelegramWebApp()) {
                // В Telegram Web App открываем в браузере
                window.Telegram.WebApp.openLink(paymentResponse.confirmation_url);
            } else {
                // В обычном браузере переходим обычным способом
                window.location.href = paymentResponse.confirmation_url;
            }
        } else {
            console.error('Некорректный ответ платежного API:', paymentResponse);
            throw new Error(paymentResponse.error || 'Ошибка при создании платежа');
        }
    } catch (error) {
        console.error('=== Ошибка при оплате документа ===');
        console.error('Error object:', error);
        console.error('Error message:', error.message);
        
        errorMessage.value = error.message || 'Во время обработки произошла ошибка, мы разбираемся с этой проблемой';
    } finally {
        loading.value = false;
    }
};

// Загрузить данные пользователя при монтировании компонента
onMounted(async () => {
    await loadUserContactData();
});
</script>

<style scoped>
.payment-panel {
    background: #ffffff;
    border-radius: 20px;
    padding: 28px;
    box-shadow: 0 4px 20px rgba(0, 0, 0, 0.08);
    border: 1px solid #f1f5f9;
    transition: all 0.3s ease;
}

.payment-panel:hover {
    box-shadow: 0 8px 30px rgba(0, 0, 0, 0.12);
    transform: translateY(-2px);
}

.payment-header {
    display: flex;
    align-items: center;
    gap: 16px;
    margin-bottom: 24px;
    padding-bottom: 16px;
    border-bottom: 2px solid #f1f5f9;
}

.payment-icon {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 48px;
    height: 48px;
    background: linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%);
    border-radius: 16px;
    color: white;
    font-size: 24px;
    flex-shrink: 0;
}

.payment-title {
    font-size: 20px;
    font-weight: 600;
    color: #1e293b;
}

.payment-content {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 24px;
    margin-bottom: 24px;
}

.payment-info {
    text-align: center;
}

.amount-label {
    font-size: 14px;
    color: #64748b;
    margin-bottom: 4px;
}

.amount-value {
    font-size: 24px;
    font-weight: 700;
    color: #1e293b;
}

/* Стили для поля email */
.email-input-section {
    margin-bottom: 16px;
}

.custom-input-wrapper {
    display: flex;
    flex-direction: column;
    gap: 8px;
}

.custom-input-label {
    font-size: 16px;
    font-weight: 600;
    color: #374151;
    margin-bottom: 4px;
}

.custom-input-container {
    position: relative;
    display: flex;
    align-items: center;
}

.custom-input {
    width: 100%;
    padding: 16px 50px 16px 20px;
    border: 2px solid #e2e8f0;
    border-radius: 16px;
    font-size: 16px;
    font-weight: 500;
    color: #1e293b;
    background: #ffffff;
    transition: all 0.2s ease;
    outline: none;
}

.custom-input:focus {
    border-color: #3b82f6;
    box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
}

.custom-input::placeholder {
    color: #9ca3af;
    font-weight: 400;
}

.input-icon {
    position: absolute;
    right: 16px;
    font-size: 20px;
    color: #64748b;
    pointer-events: none;
}

/* Стили для чекбокса согласия */
.privacy-consent-section {
    margin-bottom: 20px;
    padding: 16px 20px;
    background: #f8fafc;
    border-radius: 16px;
    border: 1px solid #e2e8f0;
}

.privacy-consent-wrapper {
    display: flex;
    align-items: flex-start;
    gap: 12px;
    cursor: pointer;
    user-select: none;
}

.privacy-checkbox {
    width: 18px;
    height: 18px;
    accent-color: #3b82f6;
    cursor: pointer;
    margin-top: 2px;
}

.privacy-consent-text {
    font-size: 14px;
    color: #374151;
    line-height: 1.4;
    flex: 1;
    font-weight: 500;
}

.privacy-consent-wrapper:hover .privacy-consent-text {
    color: #1f2937;
}

/* Стили для кнопки оплаты */
.payment-button-section {
    margin-bottom: 16px;
}

.payment-btn {
    width: 100%;
    padding: 16px 24px;
    border-radius: 12px;
    font-weight: 600;
    background: linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%);
    box-shadow: 0 4px 12px rgba(59, 130, 246, 0.3);
    transition: all 0.2s ease;
    font-size: 16px;
}

.payment-btn:hover {
    box-shadow: 0 6px 16px rgba(59, 130, 246, 0.4);
    transform: translateY(-1px);
}

.payment-btn:disabled {
    opacity: 0.6;
    transform: none;
    box-shadow: 0 2px 6px rgba(59, 130, 246, 0.2);
}

/* Стили для уведомления о территориальных ограничениях */
.payment-restriction-notice {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 8px 12px;
    background: #f8fafc;
    border: 1px solid #e2e8f0;
    border-radius: 8px;
    color: #64748b;
    font-size: 13px;
    font-weight: 500;
    margin-bottom: 12px;
}

.restriction-icon {
    color: #94a3b8;
    font-size: 16px;
    flex-shrink: 0;
}

.error-message {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-top: 16px;
    padding: 12px 16px;
    background: #fef2f2;
    border: 1px solid #fecaca;
    border-radius: 12px;
    color: #dc2626;
    font-size: 14px;
}

.error-icon {
    font-size: 18px;
    flex-shrink: 0;
}

/* Адаптивность */
@media (max-width: 768px) {
    .payment-panel {
        padding: 20px;
        border-radius: 16px;
    }
    
    .payment-content {
        flex-direction: column;
        text-align: center;
        gap: 20px;
    }
    
    .payment-btn {
        width: 100%;
        min-width: auto;
    }
    
    .payment-header {
        justify-content: center;
        text-align: center;
        margin-bottom: 20px;
    }
    
    .payment-icon {
        width: 44px;
        height: 44px;
        font-size: 20px;
    }
    
    .payment-title {
        font-size: 18px;
    }
    
    .amount-value {
        font-size: 20px;
    }

    .custom-input {
        font-size: 14px;
        padding: 14px 45px 14px 16px;
    }

    .input-icon {
        right: 14px;
        font-size: 18px;
    }

    .privacy-consent-section {
        padding: 12px 16px;
        margin-bottom: 16px;
    }

    .privacy-consent-wrapper {
        gap: 10px;
    }

    .privacy-checkbox {
        width: 16px;
        height: 16px;
    }

    .privacy-consent-text {
        font-size: 13px;
    }
}

@media (max-width: 480px) {
    .payment-panel {
        padding: 16px;
    }
    
    .payment-header {
        margin-bottom: 16px;
        padding-bottom: 12px;
    }
    
    .payment-icon {
        width: 40px;
        height: 40px;
        font-size: 18px;
    }
    
    .payment-title {
        font-size: 16px;
    }
    
    .amount-value {
        font-size: 18px;
    }
    
    .payment-btn {
        padding: 12px 20px;
        font-size: 15px;
    }

    .custom-input {
        font-size: 14px;
        padding: 12px 40px 12px 14px;
    }

    .custom-input-label {
        font-size: 14px;
    }

    .privacy-consent-section {
        padding: 10px 12px;
        margin-bottom: 14px;
    }

    .privacy-consent-text {
        font-size: 12px;
        line-height: 1.3;
    }
}
</style> 